/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prime_surgical;

import javax.swing.JOptionPane;

/**
 *
 * @author Mahmudul Hasan
 */
public class CreateUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
        initComponents();
    }
    String userName,mobile,email,password,role;
    int blankDataCheck(){
        int check=0;
        if(txtUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter User name!");
            txtUserName.requestFocus();
        }
        else if(txtMobile.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Mobile number!");
            txtMobile.requestFocus();
        }
        else if(txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Email address!");
            txtEmail.requestFocus();
        }
        else if(txtRole.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Role!");
            txtRole.requestFocus();
        }
        else if(jPasswordField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password Field is Empty!");
            jPasswordField1.requestFocus();
        }
        else{
            check=1;
        }
        return check;
    }
    void getData(){
        userName=txtUserName.getText();
        mobile=txtMobile.getText();
        email=txtEmail.getText();
        role=txtRole.getText();
        password=jPasswordField1.getText();
    }
    void fieldClear(){
        txtUserName.setText("");
        txtMobile.setText("");
        txtEmail.setText("");
        txtRole.setText("");
        jPasswordField1.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        FirstPage = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        FinalPage = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        FirstPage.setBackground(new java.awt.Color(44, 58, 71));
        FirstPage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FirstPage.setLayout(null);

        Header.setBackground(new java.awt.Color(60, 80, 104));
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Header.setForeground(new java.awt.Color(204, 204, 255));
        Header.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New User");
        Header.add(jLabel2);
        jLabel2.setBounds(0, 10, 560, 50);

        FirstPage.add(Header);
        Header.setBounds(0, -10, 560, 60);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter user name:");
        FirstPage.add(jLabel3);
        jLabel3.setBounds(200, 50, 160, 30);

        txtUserName.setBackground(new java.awt.Color(60, 80, 104));
        txtUserName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(204, 204, 204));
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FirstPage.add(txtUserName);
        txtUserName.setBounds(70, 80, 430, 40);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mobile Number:");
        FirstPage.add(jLabel4);
        jLabel4.setBounds(200, 130, 160, 30);

        txtMobile.setBackground(new java.awt.Color(60, 80, 104));
        txtMobile.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(204, 204, 204));
        txtMobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FirstPage.add(txtMobile);
        txtMobile.setBounds(70, 160, 430, 40);

        txtEmail.setBackground(new java.awt.Color(60, 80, 104));
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FirstPage.add(txtEmail);
        txtEmail.setBounds(70, 240, 430, 40);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email-Address:");
        FirstPage.add(jLabel5);
        jLabel5.setBounds(200, 210, 160, 30);

        txtRole.setBackground(new java.awt.Color(60, 80, 104));
        txtRole.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtRole.setForeground(new java.awt.Color(204, 204, 204));
        txtRole.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FirstPage.add(txtRole);
        txtRole.setBounds(70, 310, 430, 40);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Role:");
        FirstPage.add(jLabel6);
        jLabel6.setBounds(200, 280, 160, 30);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(enter at-least 6 digit strong password)");
        FirstPage.add(jLabel1);
        jLabel1.setBounds(70, 440, 260, 30);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password:");
        FirstPage.add(jLabel7);
        jLabel7.setBounds(200, 350, 160, 30);

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FirstPage.add(jButton2);
        jButton2.setBounds(30, 480, 160, 40);

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        FirstPage.add(jButton3);
        jButton3.setBounds(370, 480, 160, 40);

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton4.setText("Go to Log-in");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        FirstPage.add(jButton4);
        jButton4.setBounds(190, 480, 180, 40);

        jPasswordField1.setBackground(new java.awt.Color(60, 80, 104));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        FirstPage.add(jPasswordField1);
        jPasswordField1.setBounds(70, 380, 430, 40);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Clear all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FirstPage.add(jButton1);
        jButton1.setBounds(370, 420, 130, 40);

        jLayeredPane1.add(FirstPage, "card2");

        FinalPage.setBackground(new java.awt.Color(44, 58, 71));
        FinalPage.setLayout(null);

        jPasswordField2.setBackground(new java.awt.Color(60, 80, 104));
        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        FinalPage.add(jPasswordField2);
        jPasswordField2.setBounds(100, 100, 370, 50);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enter Admin password to confirm.");
        FinalPage.add(jLabel8);
        jLabel8.setBounds(0, 30, 560, 50);

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        FinalPage.add(jButton5);
        jButton5.setBounds(150, 160, 130, 40);

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        FinalPage.add(jButton6);
        jButton6.setBounds(280, 160, 160, 40);

        jLayeredPane1.add(FinalPage, "card3");

        getContentPane().add(jLayeredPane1);

        setSize(new java.awt.Dimension(558, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(blankDataCheck()==1){
            if(new dbConnection().singledata("SELECT `user_id` FROM `users` WHERE `user_name`='"+txtUserName.getText()+"'").isEmpty()){
            FinalPage.setVisible(true);
            FirstPage.setVisible(false);    
            }
            else{
                JOptionPane.showMessageDialog(this, "Already a user exists for this name!");
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FinalPage.setVisible(false);
        FirstPage.setVisible(true); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        getData();
        if(role.equals("Admin")||role.equals("admin")){
            JOptionPane.showMessageDialog(this, "There can be only one admin!");
            this.dispose();
        }else{
            new Login().adminPass(this, jPasswordField2, "INSERT INTO "
                + "`users`(`user_name`,`user_password`,`user_mobile`,`user_email`,`user_role`)"
                + " VALUES('"+userName+"','"+password+"','"+mobile+"','"+email+"','"+role+"')");
        FinalPage.setVisible(false);
        FirstPage.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fieldClear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        if(blankDataCheck()==1){
        FinalPage.setVisible(true);
        FirstPage.setVisible(false);   
        }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
        getData();
        if(role.equals("Admin")||role.equals("admin")){
            JOptionPane.showMessageDialog(this, "There can be only one admin!");
            this.dispose();
        }else{
            new Login().adminPass(this, jPasswordField2, "INSERT INTO "
                + "`users`(`user_name`,`user_password`,`user_mobile`,`user_email`,`user_role`)"
                + " VALUES('"+userName+"','"+password+"','"+mobile+"','"+email+"','"+role+"')");
        
        }
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FinalPage;
    private javax.swing.JPanel FirstPage;
    private javax.swing.JPanel Header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
