package prime_surgical;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahmudul Hasan
 */
public class Product_Returns extends javax.swing.JFrame {

    /**
     * Creates new form Product_Returns
     */
    public Product_Returns() {
        initComponents();
        new dbConnection().getDataFromCombo(comCategory, "SELECT `cateogory` FROM `product cateogory` order by `cateogory_id`");
        txtQuantity.setEditable(false);
        txtNewQuantity.setEditable(false);
        txtNewTotalPrice.setEditable(false);
        txtPrice.setEditable(false);
        new dbConnection().getDataFromCombo(comProduct, "SELECT `product_name` FROM `product info` group by `product_name`");
        comCategory.setEditable(false);
        comProduct.setEditable(false);
    }
    int quantity, returnQuantity, newQuantity,gr,items;
    Double price, newPrice;
    void purchaseReturn(){
        try {
        newQuantity=Integer.parseInt(txtNewQuantity.getText());
        newPrice=Double.parseDouble(txtNewTotalPrice.getText());
        gr=Integer.parseInt(comGR.getSelectedItem().toString());
        new dbConnection().updateData("UPDATE `purchase entry` SET `quantity`='"+newQuantity+"' ,`total`='"+newPrice+"' WHERE `purchase_gr`='"+gr+"'", this);
    clearData();
        } catch (Exception e) {
        }
         }
    void salesReturn(){
        newQuantity=Integer.parseInt(txtNewQuantity.getText());
        newPrice=Double.parseDouble(txtNewTotalPrice.getText());
        gr=Integer.parseInt(comGR.getSelectedItem().toString());
        new dbConnection().updateData("UPDATE `sales entry` SET `quantity`='"+newQuantity+"',`total`='"+newPrice+"' WHERE `sales_gr`='"+gr+"'", this);
   clearData();
    }
    int blankDataCheck(){
        int check=0;
        if(jComboBox2.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(this, "Select Purchase Or Sales!");
            jComboBox2.requestFocus();
        }
        else if(jComboBox3.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(this, "Select Customer!");
            jComboBox3.requestFocus();
        }
        else if(comGR.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(this, "GR Number is Missing!");
            comGR.requestFocus();
        }
        else if(comProduct.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(this, "Product Name is Missing!");
            comProduct.requestFocus();
        }
        else if(txtPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Price is Missing!");
            txtPrice.requestFocus();
        }
        else if(txtQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Quantity is Missing!");
            txtQuantity.requestFocus();
        }
        else if(txtReturn.getText().isEmpty() || Integer.parseInt(txtReturn.getText())<=0){
            JOptionPane.showMessageDialog(this, "Please Enter Return Quantity!");
            txtReturn.requestFocus();
        }
        else if(txtNewQuantity.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "New Quantity is Missing!");
        }
        else if(txtNewTotalPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "New Price is Missing!");
        }
        else {
            check=1;
        }
        return check;
    }
    void clearData(){
        comBill.setSelectedIndex(0);
        comGR.setSelectedIndex(0);
        comCategory.setSelectedIndex(0);
        comProduct.setSelectedIndex(0);
        txtPrice.setText("0.00");
        txtQuantity.setText("0");
        txtReturn.setText("0");
        txtNewQuantity.setText("0");
        txtNewTotalPrice.setText("0.00");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        comBill = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        comProduct = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtReturn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNewQuantity = new javax.swing.JTextField();
        txtNewTotalPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        comCategory = new javax.swing.JComboBox<>();
        comGR = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbDue = new javax.swing.JLabel();
        lbSubTotal = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbPaid = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(50, 68, 105));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(50, 68, 105));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 30, 100);

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product Returns");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 0, 280, 90);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1300, 10, 60, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 90);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(null);

        comBill.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comBill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comBill.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comBillPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(comBill);
        comBill.setBounds(20, 140, 190, 40);

        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Purchase", "Sales" }));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jComboBox2ComponentMoved(evt);
            }
        });
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(20, 10, 360, 50);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GR:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(210, 110, 170, 30);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cateogory:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(120, 180, 130, 30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Product:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(120, 250, 130, 30);

        txtPrice.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPrice.setText("0.00");
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel4.add(txtPrice);
        txtPrice.setBounds(20, 360, 200, 40);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Price:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 330, 130, 30);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Quantity:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(220, 330, 130, 30);

        txtQuantity.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtQuantity.setText("0");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel4.add(txtQuantity);
        txtQuantity.setBounds(220, 360, 160, 40);

        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(20, 60, 360, 50);

        comProduct.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel4.add(comProduct);
        comProduct.setBounds(20, 280, 360, 40);

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Return:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 420, 130, 30);

        txtReturn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtReturn.setText("0");
        txtReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReturnMouseClicked(evt);
            }
        });
        txtReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnActionPerformed(evt);
            }
        });
        txtReturn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReturnKeyReleased(evt);
            }
        });
        jPanel4.add(txtReturn);
        txtReturn.setBounds(20, 450, 200, 40);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("New Quantity:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(220, 420, 160, 30);

        txtNewQuantity.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNewQuantity.setText("0");
        txtNewQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewQuantityActionPerformed(evt);
            }
        });
        jPanel4.add(txtNewQuantity);
        txtNewQuantity.setBounds(220, 450, 160, 40);

        txtNewTotalPrice.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNewTotalPrice.setText("0.00");
        jPanel4.add(txtNewTotalPrice);
        txtNewTotalPrice.setBounds(30, 530, 340, 50);

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("New Total Price:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(110, 500, 200, 30);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("Return");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(70, 590, 260, 50);

        comCategory.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comCategory.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comCategoryPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(comCategory);
        comCategory.setBounds(20, 210, 360, 40);

        comGR.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comGR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel4.add(comGR);
        comGR.setBounds(210, 140, 170, 40);

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Bill:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(20, 110, 190, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 110, 400, 650);

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL", "GR", "Cateogory", "Product", "Price", "Quantity", "Total"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 110, 940, 490);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sub Total:");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(0, 0, 90, 40);

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Discount:");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(0, 40, 90, 40);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Due:");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(0, 120, 90, 40);

        lbDue.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbDue.setForeground(new java.awt.Color(0, 0, 0));
        lbDue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDue.setText("0.00");
        jPanel9.add(lbDue);
        lbDue.setBounds(100, 120, 210, 40);

        lbSubTotal.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lbSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSubTotal.setText("0.00");
        jPanel9.add(lbSubTotal);
        lbSubTotal.setBounds(100, 0, 210, 40);

        lbDiscount.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(0, 0, 0));
        lbDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDiscount.setText("0.00");
        jPanel9.add(lbDiscount);
        lbDiscount.setBounds(100, 40, 210, 40);

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Paid:");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(0, 80, 90, 40);

        lbPaid.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbPaid.setForeground(new java.awt.Color(0, 0, 0));
        lbPaid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPaid.setText("0.00");
        jPanel9.add(lbPaid);
        lbPaid.setBounds(100, 80, 210, 40);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(1040, 600, 320, 170);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("Exit");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(620, 620, 260, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jComboBox2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ComponentMoved

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() > 0 && jComboBox2.getSelectedIndex() == 1) {
            new dbConnection().getDataFromCombo(jComboBox3, "SELECT `supplier_company_name` FROM `suppliers`");
        }
        if (jComboBox2.getSelectedIndex() > 0 && jComboBox2.getSelectedIndex() == 2) {
            new dbConnection().getDataFromCombo(jComboBox3, "SELECT `customer_name` FROM `sales entry` where `bill_no`>0 GROUP BY `customer_name` ORDER BY `bill_no`");
        }
        if (jComboBox2.getSelectedIndex() == 0) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            jComboBox3.setSelectedIndex(0);
            comBill.setSelectedIndex(0);
        }

    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() > 0 && jComboBox2.getSelectedIndex() == 1) {
            String companyName = jComboBox3.getSelectedItem().toString();
            new dbConnection().getDataFromCombo(comBill, "SELECT `bill_no` FROM `purchase entry` WHERE `company_name`='" + companyName + "' GROUP BY `bill_no` ORDER BY `bill_no`");
            new dbConnection().getDataFromCombo(comGR, "SELECT `purchase_gr` FROM `purchase entry` WHERE `company_name`='"+companyName+"'");
            new dbConnection().showPurchaseEntry("SELECT * FROM `purchase entry` WHERE `company_name`= '" + companyName + "'", jTable1);
            lbSubTotal.setText(new dbConnection().singledata("SELECT SUM(`total`) FROM `purchase entry` WHERE `company_name`= '" + companyName + "'"));
            lbPaid.setText(new dbConnection().singledata("SELECT SUM(`paid`) FROM `purchase accounts` WHERE `company`= '" + companyName + "'"));
            lbDiscount.setText(new dbConnection().singledata("SELECT SUM(`discount`) FROM `purchase accounts` WHERE `company`= '" + companyName + "'"));
            lbDue.setText(new dbConnection().singledata("SELECT SUM(`purchase accounts`.`total`-`purchase accounts`.`paid`) AS due\n"
                    + "FROM `purchase accounts` WHERE `company`='" + companyName + "'"));
        } else if (jComboBox2.getSelectedIndex() > 0 && jComboBox2.getSelectedIndex() == 2) {
            String companyName = jComboBox3.getSelectedItem().toString();
            new dbConnection().getDataFromCombo(comBill, "SELECT `bill_no` FROM `sales entry` WHERE `customer_name`='" + companyName + "' GROUP BY `bill_no` ORDER BY `bill_no`");
            new dbConnection().getDataFromCombo(comGR, "SELECT `sales_gr` FROM `sales entry` WHERE `customer_name`='"+companyName+"'");
            new dbConnection().showPurchaseEntry("SELECT * FROM `sales entry` WHERE `customer_name`= '" + companyName + "'", jTable1);
            lbSubTotal.setText(new dbConnection().singledata("SELECT SUM(`total`) FROM `sales entry` WHERE `customer_name`='" + companyName +"'"));
            lbPaid.setText(new dbConnection().singledata("SELECT SUM(`paid`) FROM `sales accounts` WHERE `customer`= '"+companyName+"'"));
            lbDiscount.setText(new dbConnection().singledata("SELECT SUM(`discount`) FROM `sales accounts` WHERE `customer`= '" +companyName+ "'"));
            lbDue.setText(new dbConnection().singledata("SELECT SUM(`due`) FROM `sales accounts` WHERE `customer`= '"+companyName +"'"));
        }
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void comBillPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comBillPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() == 1) {
            String companyName = jComboBox3.getSelectedItem().toString();
            new dbConnection().showPurchaseEntry("SELECT * FROM `purchase entry` WHERE `company_name`= '" + companyName + "' and bill_no='"+comBill.getSelectedItem().toString()+"'", jTable1);
            lbSubTotal.setText(new dbConnection().singledata("SELECT SUM(`total`) FROM `purchase entry` WHERE `company_name`= '" + companyName + "'"));
            lbPaid.setText(new dbConnection().singledata("SELECT SUM(`paid`) FROM `purchase accounts` WHERE `company`= '" + companyName + "'"));
            lbDiscount.setText(new dbConnection().singledata("SELECT SUM(`discount`) FROM `purchase accounts` WHERE `company`= '" + companyName + "'"));
            lbDue.setText(new dbConnection().singledata("SELECT SUM(`purchase accounts`.`total`-`purchase accounts`.`paid`) AS due\n"
                    + "FROM `purchase accounts` WHERE `company`='" + companyName + "'"));
        } else if (jComboBox2.getSelectedIndex()==2) {
            String companyName = jComboBox3.getSelectedItem().toString();
            String Bill = comBill.getSelectedItem().toString();
            new dbConnection().showPurchaseEntry("SELECT * FROM `sales entry` WHERE `bill_no`='" + comBill.getSelectedItem().toString() + "' and `customer_name`='" + companyName + "' ", jTable1);
            lbSubTotal.setText(new dbConnection().singledata("SELECT SUM(`total`) FROM `sales entry` WHERE `customer_`= '" + companyName + "'"));
            lbPaid.setText(new dbConnection().singledata("SELECT SUM(`paid`) FROM `sales accounts` WHERE `customer`= '" + companyName + "' AND `bill_no`='" + Bill + "'"));
            lbDiscount.setText(new dbConnection().singledata("SELECT SUM(`discount`) FROM `sales accounts` WHERE `customer`= '" + companyName + "' AND `bill_no`='" + Bill + "'"));
            lbDue.setText(new dbConnection().singledata("SELECT SUM(`sales accounts`.`total`-`sales accounts`.`paid`) AS due\n"
                    + "FROM `sales accounts` WHERE `bill_no`='" + Bill + "' AND `company`='" + companyName + "'"));
        }
    }//GEN-LAST:event_comBillPopupMenuWillBecomeInvisible

    private void comCategoryPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comCategoryPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String productCategoryId = new dbConnection().singledata("SELECT `cateogory_id` FROM `product cateogory` WHERE `cateogory`='" + comCategory.getSelectedItem().toString() + "'");
        new dbConnection().getDataFromCombo(comProduct, "SELECT `product_name` FROM `product info` where `product_category_id`='" + productCategoryId + "'");
    }//GEN-LAST:event_comCategoryPopupMenuWillBecomeInvisible

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        comCategory.setSelectedItem(dtm.getValueAt(jTable1.getSelectedRow(), 2).toString());
        comProduct.setSelectedItem(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());
        txtPrice.setText(dtm.getValueAt(jTable1.getSelectedRow(), 4).toString());
        txtQuantity.setText(dtm.getValueAt(jTable1.getSelectedRow(), 5).toString());
        comGR.setSelectedItem(dtm.getValueAt(jTable1.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(blankDataCheck()==1){
            if(jComboBox2.getSelectedIndex()==1){
                purchaseReturn();
            }
            else if(jComboBox2.getSelectedIndex()==2){
                salesReturn();
            }}
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnActionPerformed

    private void txtReturnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReturnKeyReleased
        // TODO add your handling code here:
        try {
            quantity = Integer.parseInt(txtQuantity.getText());
            returnQuantity = Integer.parseInt(txtReturn.getText());
            if (returnQuantity <= quantity) {
                newQuantity = quantity - returnQuantity;
                txtNewQuantity.setText("" + newQuantity);
                newPrice = newQuantity * Double.parseDouble(txtPrice.getText());
                txtNewTotalPrice.setText("" + newPrice);
            }
        } catch (Exception e) {
            txtNewQuantity.setText("" + 0);
            txtNewTotalPrice.setText("" + 0.00);
        }
    }//GEN-LAST:event_txtReturnKeyReleased

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtNewQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewQuantityActionPerformed

    private void txtReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReturnMouseClicked
        // TODO add your handling code here:
        txtReturn.setText("");
    }//GEN-LAST:event_txtReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Returns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comBill;
    private javax.swing.JComboBox<String> comCategory;
    private javax.swing.JComboBox<String> comGR;
    private javax.swing.JComboBox<String> comProduct;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbDue;
    private javax.swing.JLabel lbPaid;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JTextField txtNewQuantity;
    private javax.swing.JTextField txtNewTotalPrice;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReturn;
    // End of variables declaration//GEN-END:variables
}
